import Config

# Configure your database. The application runs with the restricted role by
# default; migration tasks explicitly opt into the owner role.
database_role_mode = System.get_env("CLUBEIRA_DATABASE_ROLE_MODE", "runtime")

{database_url, database_role_options} =
  case database_role_mode do
    "runtime" ->
      url =
        System.get_env("CLUBEIRA_DATABASE_URL") ||
          "ecto://clubeira_app:clubeira_app@localhost:55432/clubeira_dev"

      {url, after_connect: {Clubeira.Repo.RuntimeRole, :validate_connection!, []}}

    "migrator" ->
      url =
        System.get_env("CLUBEIRA_MIGRATOR_DATABASE_URL") ||
          "ecto://clubeira_migrator:clubeira_migrator@localhost:55432/clubeira_dev"

      {url, []}

    invalid ->
      raise """
      invalid CLUBEIRA_DATABASE_ROLE_MODE=#{inspect(invalid)}; expected runtime or migrator
      """
  end

config :clubeira,
       Clubeira.Repo,
       [
         url: database_url,
         stacktrace: true,
         show_sensitive_data_on_connection_error: true,
         pool_size: 10
       ] ++ database_role_options

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :clubeira, ClubeiraWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: String.duplicate("development-only-", 4),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:clubeira, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:clubeira, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :clubeira, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
